2023.3.x feature auth bg image
cortezaproject/corteza-webapp-admin pull request #131
Opened 2022-11-03 10:25 UTC by KinyaElGrande

Add support for uploading auth screen background image and styles .

2022-11-03 10:31 UTC, KinyaElGrande commented
![](https://github.trello.services/images/mini-trello-icon.png) [Auth background image](https://trello.com/c/FyrM0Z7o/3316-auth-background-image)

2022-11-03 15:31 UTC, Fajfa requested changes

2022-11-03 15:31 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +  <b-container class="py-3">
Why did you move it into one line?

2022-11-03 15:31 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +    <c-content-header :title="$t('title')" />
Same here

2022-11-03 15:31 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +      @submit="onAuthBgStylesSubmit"
onAuthBackgroundSubmit

2022-11-03 15:31 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +    settings: {
Instead of this please use the same approach as getAuth

Or if you wanna do it properly properly. Then when settings are fetched (not on watcher) compute both of the values needed for each component.

2022-11-03 15:31 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +      bgSettings: {},
no need for extra property since when you fetch you recompute it anyways (similar to getAuth)

2022-11-03 15:31 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +      authBgStyles: {
rename to just authBackground please

2022-11-03 15:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +      this.$set(this.settings, name, value)
You shouldn't set properties in children, instead emit an event that updates that property

2022-11-03 15:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +          this.$set(this.settings, name, undefined)
Same here

2022-11-04 15:03 UTC, Fajfa requested changes
Smaller fixes, otherwise seems good

2022-11-04 15:03 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +      :settings="getAuthBackround"
Typo here getAuthBackground

2022-11-04 15:03 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +          this.toastSuccess(
No need for this in multiple lines, one line is enough. Same for all other occurences of this in the file

2022-11-04 15:03 UTC, Fajfa commented on src/views/System/Settings/Index.vue
> +  mixins: [editorHelpers],
This should be in multiple lines like it was before

2022-11-15 14:31 UTC, Fajfa requested changes
Smaller code lint/best practices changes. After that, ready to merge

2022-11-15 14:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +    class="shadow-sm"
Class should be last of the options (except if style exists that should be last)
And after that there should only be events (@)

2022-11-15 14:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +            </h5>
Empty line between elements inside same element

2022-11-15 14:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +      </b-col>
Empty line

2022-11-15 14:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +          </h5>
Empty line

2022-11-15 14:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +          <c-submit-button
Empty line

2022-11-15 14:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +            class="float-right mt-2"
Class last before events

2022-11-15 14:31 UTC, Fajfa commented on src/components/Settings/System/CSystemEditorAuthBgScreen.vue
> +    <template #header>
Move this to the top of the card since its the title

2022-11-16 12:14 UTC, Fajfa approved these changes

2022-11-18 10:11 UTC, merged