Create a user friendly layout for multiple apigw headers
cortezaproject/corteza-webapp-admin pull request #82
Opened 2021-10-26 05:38 UTC by MarioBur

2021-10-26 06:29 UTC, darh requested changes

2021-10-26 06:29 UTC, darh commented on src/components/Apigw/CHeaders.vue
> +    toHeadersArray (value) {
this parser is too optimistic

2021-10-26 06:29 UTC, darh commented on src/components/Apigw/CHeaders.vue
> +.w-45{
apply appropriate code formatting

2021-10-26 06:29 UTC, darh commented on src/components/Apigw/CHeaders.vue
> +            <b-form-input
indent?

2021-10-26 06:29 UTC, darh commented on src/components/Apigw/CFilterParams.vue
> +        <c-headers
why `c-` prefix?

2021-10-26 06:46 UTC, Fajfa commented on src/components/Apigw/CHeaders.vue
> +        }).join(' and ')
Can we have `(` between anded expressions?? Also not sure but does `and` have to be `AND`? Check with Peter

2021-10-26 07:02 UTC, tjerman requested changes
I also have a few change requests in regards to how the headers are managed.

2021-10-26 07:02 UTC, tjerman commented on src/components/Apigw/CFilterParams.vue
> +          v-if="label === 'Header'"
This v-if seems volatile to me; what if we change the translation content to something else?
Please use a system-defined key, so for example from the following set of things:

```
[{ label: 'Header', key: 'header' }, { label: 'Param', key: 'param' }]
```

you would use the `key` parameter instead of the `label` parameter.

2021-10-26 07:02 UTC, tjerman commented on src/components/Apigw/CHeaders.vue
> +      if (this.headers[index].label === this.$t(`filters.headers.custom`)) {
I would prefer not to see translation strings being compared.
IIRC, the Vue-select component has an event when the value is selected, so you could easily refactor this into something that could use system-defined values to determine if something is custom or not.

2021-10-26 07:02 UTC, tjerman commented on src/components/Apigw/CHeaders.vue
> +    sortedHeaderList () {
This bit doesn't need such complexity.
You can move the above list of headers into a computed property in an already sorted manner.

2021-10-26 07:02 UTC, tjerman commented on src/components/Apigw/CHeaders.vue
> +    },
Out of pure caution and future-proofing, I would prefer to see this computed property into a method (make sure to correct the property call to a method call).
Having it become a method makes it return a fresh instance of the object every time instead of reusing the same one.

If we extend the header definition and add some nested values passed as a reference to the above object, that object will be reused and the code will not work anymore.
For example:

```
{ label: '', custom: false, value: '', new1: [], new2: {}, new3: new Set([]) }
```

All three of the newly added properties would be passed as references and reused.

2021-10-26 07:16 UTC, MarioBur commented on src/components/Apigw/CFilterParams.vue
> +        <c-headers
I looked in other components in admin and they mostly use c- prefix so I thought that, that was the standard syntax we use. I have added c- prefix to other components in apigw, should the c- be removed there as well?

2021-11-12 08:39 UTC, petergrlica commented
This is no longer current, simplification was done here: https://github.com/cortezaproject/corteza-webapp-admin/pull/83
Closing

2021-11-12 08:39 UTC, closed without merging